apiVersion: v1
kind: Service
metadata:
  name: oyashiro-service
  namespace: oyashiro
spec:
  ports:
  - name: "http"
    protocol: "TCP"
    port: 80
    targetPort: 6080
  selector:
    app: sengu-toolkit-docker
