apiVersion: apps/v1
kind: Deployment
metadata:
  name: oyashiro-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: sengu-toolkit-docker
  template:
    metadata:
      labels:
        app: sengu-toolkit-docker
    spec:
      initContainers:
      - name: sengu-toolkit-docker-container-copyhome
        image: nord14541/sengu-toolkit-docker:latest
        imagePullPolicy: Always
        volumeMounts:
        - mountPath: /home/newuser
          name: home
        command: ['sh', '-c', 'cp -r /home/oyashiro_user/.config /home/newuser']
      containers:
      - name: sengu-toolkit-docker-container
        image: nord14541/sengu-toolkit-docker:latest
        imagePullPolicy: Always
        volumeMounts:
        - mountPath: /home/oyashiro_user
          name: home
        env:
        - name: TZ
          valueFrom:
            configMapKeyRef:
              name: locale
              key: timezone 
      - name: resilio-container
        image: resilio/sync
        volumeMounts:
        - mountPath: /mnt/sync
          name: home
        env:
        - name: TZ
          valueFrom:
            configMapKeyRef:
              name: locale
              key: timezone 
        - name: PUID
          valueFrom:
            configMapKeyRef:
              name: id
              key: uid 
        - name: PGID
          valueFrom:
            configMapKeyRef:
              name: id
              key: gid 
      volumes:
      - name: home
        persistentVolumeClaim:
          claimName: oyashiro-pvc
